version: '3'

services:
  cache:
    container_name: redis_decorator
    image: redis
    networks:
      - redis_decorator_net
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

networks:
  redis_decorator_net:
    driver: bridge
